// src/services/loanService.ts
import type { LoanApplication } from "@/types/loan";

// This would be replaced with actual API calls in the real implementation
export async function getLoanApplications(): Promise<LoanApplication[]> {
  // In production, this would fetch from your API endpoint
  // For now, we'll return mock data
  return [
    {
      id: "1",
      farmerId: "farmer-123",
      loanAmount: 5000,
      purpose: "seeds",
      duration: "6months",
      cropTypes: ["rice", "wheat"],
      landSize: "10",
      landUnit: "acres",
      landLocation: "Northern Plains",
      landOwnership: "owned",
      farmingExperience: "8 years",
      previousLoans: true,
      previousLoanDetails:
        "One loan for irrigation system in 2023, fully repaid",
      expectedYield: "40 quintals per acre",
      documents: {
        identityProof: null,
        landRecord: null,
        previousHarvestProof: null,
        bankStatement: null,
      },
      additionalInfo:
        "Seeking funding for high-quality seeds and fertilizers for this season",
      agreeToTerms: true,
      status: "under_review",
      creditScore: 720,
      weatherRiskAssessment:
        "Low risk based on historical weather patterns in this region",
      createdAt: new Date("2025-01-15"),
      updatedAt: new Date("2025-01-15"),
      appliedAt: "2025-01-15",
      cropType: ["rice", "wheat"],
    },
    {
      id: "2",
      farmerId: "farmer-456",
      loanAmount: 12000,
      purpose: "equipment",
      duration: "2years",
      cropTypes: ["wheat", "maize"],
      landSize: "15",
      landUnit: "acres",
      landLocation: "Central Valley",
      landOwnership: "leased",
      farmingExperience: "5 years",
      previousLoans: false,
      previousLoanDetails: "",
      expectedYield: "35 quintals per acre",
      documents: {
        identityProof: null,
        landRecord: null,
        previousHarvestProof: null,
        bankStatement: null,
      },
      additionalInfo:
        "Need to purchase a new tractor for more efficient farming",
      agreeToTerms: true,
      status: "under_review",
      creditScore: 680,
      weatherRiskAssessment:
        "Medium risk due to occasional drought in summer months",
      createdAt: new Date("2025-02-01"),
      updatedAt: new Date("2025-02-01"),
      appliedAt: "2025-02-01",
      cropType: ["rice", "wheat"],
    },
    {
      id: "3",
      farmerId: "farmer-789",
      loanAmount: 7500,
      purpose: "irrigation",
      duration: "1year",
      cropTypes: ["vegetables", "fruits"],
      landSize: "5",
      landUnit: "acres",
      landLocation: "Southern Coast",
      landOwnership: "owned",
      farmingExperience: "12 years",
      previousLoans: true,
      previousLoanDetails: "Multiple loans in the past, all repaid on time",
      expectedYield: "Varied across crops",
      documents: {
        identityProof: null,
        landRecord: null,
        previousHarvestProof: null,
        bankStatement: null,
      },
      additionalInfo:
        "Installing drip irrigation system to improve water efficiency",
      agreeToTerms: true,
      status: "under_review",
      creditScore: 750,
      weatherRiskAssessment: "Low risk for irrigation projects in this region",
      createdAt: new Date("2025-02-10"),
      updatedAt: new Date("2025-02-10"),
      appliedAt: "2025-02-10",
      cropType: ["rice", "wheat"],
    },
    {
      id: "4",
      farmerId: "farmer-101",
      loanAmount: 20000,
      purpose: "storage",
      duration: "3years",
      cropTypes: ["rice", "pulses"],
      landSize: "25",
      landUnit: "acres",
      landLocation: "Eastern Highlands",
      landOwnership: "owned",
      farmingExperience: "15 years",
      previousLoans: true,
      previousLoanDetails: "One ongoing loan for land purchase",
      expectedYield: "45 quintals per acre for rice, 20 for pulses",
      documents: {
        identityProof: null,
        landRecord: null,
        previousHarvestProof: null,
        bankStatement: null,
      },
      additionalInfo: "Building storage facility to reduce post-harvest losses",
      agreeToTerms: true,
      status: "under_review",
      creditScore: 710,
      weatherRiskAssessment: "Low risk with occasional heavy rainfall",
      createdAt: new Date("2025-02-15"),
      updatedAt: new Date("2025-02-15"),
      appliedAt: "2025-02-15",
      cropType: ["rice", "wheat"],
    },
    {
      id: "5",
      farmerId: "farmer-202",
      loanAmount: 8000,
      purpose: "marketing",
      duration: "1year",
      cropTypes: ["spices", "tea"],
      landSize: "8",
      landUnit: "acres",
      landLocation: "Western Ghats",
      landOwnership: "leased",
      farmingExperience: "7 years",
      previousLoans: false,
      previousLoanDetails: "",
      expectedYield: "Specialty crops with premium pricing",
      documents: {
        identityProof: null,
        landRecord: null,
        previousHarvestProof: null,
        bankStatement: null,
      },
      additionalInfo: "Developing direct-to-consumer marketing channels",
      agreeToTerms: true,
      status: "under_review",
      creditScore: 690,
      weatherRiskAssessment: "Medium risk with good irrigation infrastructure",
      createdAt: new Date("2025-02-20"),
      updatedAt: new Date("2025-02-20"),
      appliedAt: "2025-02-20",
      cropType: ["rice", "wheat"],
    },
    {
      id: "6",
      farmerId: "farmer-303",
      loanAmount: 15000,
      purpose: "diversification",
      duration: "3years",
      cropTypes: ["fruits", "vegetables", "spices"],
      landSize: "12",
      landUnit: "acres",
      landLocation: "Midwestern Region",
      landOwnership: "owned",
      farmingExperience: "10 years",
      previousLoans: true,
      previousLoanDetails: "Two previous loans, all repaid",
      expectedYield: "Mixed yield across diverse crops",
      documents: {
        identityProof: null,
        landRecord: null,
        previousHarvestProof: null,
        bankStatement: null,
      },
      additionalInfo: "Converting to organic farming with multiple crop types",
      agreeToTerms: true,
      status: "under_review",
      creditScore: 730,
      weatherRiskAssessment: "Low risk with diversified crop portfolio",
      createdAt: new Date("2025-03-01"),
      updatedAt: new Date("2025-03-01"),
      appliedAt: "2025-03-01",
      cropType: ["rice", "wheat"],
    },
  ];
}

export async function getLoanApplicationById(
  id: string
): Promise<LoanApplication | null> {
  const loans = await getLoanApplications();
  return loans.find((loan) => loan.id === id) || null;
}
